source "https://rubygems.org"

#gem "github-pages", group: :jekyll_plugins
gem 'json'


gem "minimal-mistakes-jekyll"
gem "wdm", "~> 0.1.0" if Gem.win_platform?

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'jekyll-lunr-js-search'
  gem 'nokogiri', '~> 1.6.0'     # 1.7 requires ruby >= 2.1.0
  gem 'classifier-reborn'        # --lsi support
  gem 'rb-gsl'                   # make lsi faster.  Don't forget brew install gsl
#  gem 'jekyll-paginate'
#  gem 'jekyll-sitemap'
#  gem 'jekyll-gist'
#  gem 'jekyll-feed'
#  gem 'jemoji'
end